version: '3'

services:
  api:
    build: ./api 
    volumes: 
      - ./api:/bin
    ports:
      - 8080:8080
    networks:
      - webproxy


    hostname: api
  calc-server:
    build: ./server
    volumes:
      - ./server:/bin_serv
    ports:
      - "8081:8081"
    networks:
      - webproxy
  
networks:
  webproxy:
    driver: bridge
